language: node_js
node_js:
  - node

notifications:
  slack:
    secure: jVT16bS1/quqyFgWs6vcc2hnuFDhCVk2q0FoRFSREaHhrVMivlOKvZw9hJ8eI47AOUedtKr2e/zOkMMs+DrtDrTD6xeIKaw9nod7t4f816eL51tD7C+arfEOsVibyj+3wzFmCg34MTFqQrx7v8Rn27jUlLsEh3RdgTITFGwd/+VI7nZeHy/NdvmVMsGeX1osOtXvai66KAhw7mBcts8iynn9zpCRjZ+uWjV8oXVgn6Rn82DjA+nrJAuEwhI3KvN094ibmotLzrZWuVUDGLqYAmG+jhKq4N5TkLiHhHc1ZAfu0djruGmdaZ99tdApVCTwdVHEykpap0xDhLjvdLSh0ypMuVFDtxlsvgcIS0i5GXtsmvbrM1aT5ExJi1zZjWXBtBfpiy+B+IEeVga776k2wOSXaFlpC4+wTgUndR1qZKC2T3lPkVJq9g4dNCJd8xB9JCxjWRKYRlLOIgO23XYXrGXrlGZ5s5iGvQHgEyx4RJgqpx0I4Z6nB0K461q8dp4J9kXg0lZblaNrtgvMnpan6qqqgF+hdehSxVo0svefasw7oose9neLfyj6KIztr93eetvo1FXr56PIHTe5zKwAsLtYmf7wjCoGa5jxO3dANMbfNOr0bkO8Qy3IFmuW16NROT0ImU542FbwB5SYmET08eOmN4lwxpSormzqJO0oE0Q=
    exclude:
      if: (fork = true)

install:
  - npm install
  - npm install -g codecov

script:
  - npm run test

after_success:
  - codecov
